import { Geist, Geist_Mono, Kanit, Space_Grotesk } from "next/font/google";
import "./globals.css";
import "./media.css";
import { LanguageProvider } from "./context/LanguageContext";
import Link from "next/link";
import { RiHome4Line } from "react-icons/ri";
import { PiArticleNyTimes } from "react-icons/pi";
import { SiBookstack } from "react-icons/si";
import { FaTeamspeak } from "react-icons/fa6";
import { TfiWrite } from "react-icons/tfi";
import { IoIosSettings } from "react-icons/io";
import { FaEarListen } from "react-icons/fa6";
// import { FiSidebar } from "react-icons/fi";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const kanit = Kanit({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

const spaceGrotesk = Space_Grotesk({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: "Gryphon school",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/x-icon" href="logo2.jpg" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${kanit.className} ${spaceGrotesk.className} antialiased`}
      >
        <LanguageProvider>
          <div className="layout">
            <div className="sidebar">
              {/* <div className="side">
                <FiSidebar style={{ width: '20px', height: '20px' }} />
              </div> */}
              <div className="logo" />
              <nav className="nav">
                <Link href="/home" className="nav-item"><RiHome4Line style={{ width: '25px', height: '25px' }} />Bosh Sahifa</Link>
                <Link href="/articles" className="nav-item"><PiArticleNyTimes style={{ width: '25px', height: '25px' }} /> Articles</Link>
                <Link href="/books" className="nav-item"><SiBookstack style={{ width: '25px', height: '25px' }} /> Kitoblar</Link>
                <Link href="/listning" className="nav-item"><FaEarListen style={{ width: '25px', height: '25px' }} /> Listening</Link>
                <Link href="/speaking" className="nav-item"><FaTeamspeak style={{ width: '25px', height: '25px' }} /> Speaking</Link>
                <Link href="/writing" className="nav-item"><TfiWrite style={{ width: '25px', height: '25px' }} /> Writing</Link>
                <Link href="/seting" className="nav-item"><IoIosSettings style={{ width: '25px', height: '25px' }} /> Sozlamalar</Link>
              </nav>
            </div>
            <main className="main-content">{children}</main>
          </div>
        </LanguageProvider>
      </body>
    </html>
  );
}
